<Project>
    <PropertyGroup>
        <BuildTimestampVersion Condition="'$(BuildTimestampVersion)' == ''">$([System.DateTime]::Now.ToString('yyyy.M.d.HHmm'))</BuildTimestampVersion>
        <Version>$(BuildTimestampVersion)</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <InformationalVersion>v$(Version)</InformationalVersion>
    </PropertyGroup>
</Project>
